# Generated by Django 4.2.13 on 2024-08-23 17:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_journalentry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='date',
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('habit_logs', models.ManyToManyField(to='api.habitlog')),
                ('journal_entry', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.journalentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
