# Generated by Django 4.2.13 on 2024-08-23 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_habitlog_date_remove_journalentry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
