# Generated by Django 4.2.13 on 2024-08-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_dailylog_habit_logs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='habit_logs',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='api.habitlog'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='journal_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.journalentry'),
        ),
    ]
