# Generated by Django 4.2.13 on 2024-08-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_dailylog_habit_logs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='habit_logs',
            field=models.ManyToManyField(blank=True, default=(), null=True, to='api.habitlog'),
        ),
    ]
