# Generated by Django 4.2.13 on 2024-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_dailylog_habit_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='habit_logs',
            field=models.ManyToManyField(blank=True, null=True, to='api.habitlog'),
        ),
    ]
