# Generated by Django 4.2.13 on 2024-09-01 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_dailylog_habit_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
