# Generated by Django 4.2.13 on 2024-09-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
    ]
